### ISSUE TITLE
Cannot construct Camunda8 using explicit configuration

### ISSUE THREAD

**Issue by jwulf** [camunda/camunda-8-js-sdk#153]
With no `CAMUNDA_OAUTH_URL` set in the env, constructing a Camunda8 object like this: 

```javascript
const camundaSdk = require('@camunda8/sdk');
const camunda = new camundaSdk.Camunda8({
  config: {
    ZEEBE_ADDRESS: 'zeebeAddress',
    ZEEBE_CLIENT_ID: 'camundaClientId',
    ZEEBE_CLIENT_SECRET: 'camundaClientSecret',
//    ZEEBE_AUTHORIZATION_SERVER_URL: 'https://login.cloud.camunda.io/oauth/token',
    CAMUNDA_OAUTH_URL: 'https://login.cloud.camunda.io/oauth/token'
  }
});
```

Throws:

```
Error: Missing required configuration CAMUNDA_OAUTH_URL. Please supply this value as an environment variable or configuration object field.
    at RequireConfiguration (/Users/jwulf/workspace/tmp/action-test/node_modules/@camunda8/sdk/dist/lib/RequireConfiguration.js:6:15)
    at new OAuthProvider (/Users/jwulf/workspace/tmp/action-test/node_modules/@camunda8/sdk/dist/oauth/lib/OAuthProvider.js:48:61)
    at new Camunda8 (/Users/jwulf/workspace/tmp/action-test/node_modules/@camunda8/sdk/dist/c8/index.js:36:34)
    at Object.<anonymous> (/Users/jwulf/workspace/tmp/action-test/index.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by jwulf** [comment]
Reproducer here: https://github.com/jwulf/repro-153

**Comment by jwulf** [comment]
The OAuthProvider test should contain a test that scrubs the env and hydrates only through explicit config.

The smoke test needs to instantiate an OAuth component. 

It also needs to scrub the process environment vars to test explicit configuration.

**Comment by pepopowitz** [comment]
@jwulf and I paired and we think it's an issue with how the configuration object is being passed in.

When I construct the object like this, I get no errors: 

```javascript
const camunda = new Camunda8({
	ZEEBE_ADDRESS: 'zeebeAddress',
	ZEEBE_CLIENT_ID: 'camundaClientId',
	ZEEBE_CLIENT_SECRET: 'camundaClientSecret',
	CAMUNDA_OAUTH_URL: 'https://login.cloud.camunda.io/oauth/token',
})
```

The README.md suggests passing the configuration as a `config` property, but in fact the constructor actually wants the configuration as the only argument.
